# Site settings
name: andyiac
title: andyiac
nickname: andyiac
description: andyiac's blog
author: andyiac
twitter_username: andyiac
github_username: andyiac

# Build settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

IMG_PATH: http://freshstu.qiniudn.com

baseurl: ""
# url: "http://www.andyiac.com"
url: "http://blog.andyiac.com"
permalink: /:year/:month/:title/
