name: "Andyiac"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]
baseurl: ''

# Information for the Atom feed
andyiac:
   author: "andyiac"
   email: "andyiac@xxx.com"