name: "Andyiac"
markdown: kramdown # redcarpet
highlighter: rouge # pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]
baseurl: ''

# Information for the Atom feed
andyiac:
   author: "andyiac"
   email: "andyiaczhang@gmail.com"
